// Mocks generated by Mockito 5.0.15 from annotations
// in tv_shows/test/presentation/pages/popular_tv_shows_page_test.dart.
// Do not manually edit this file.

import 'package:bloc_test/bloc_test.dart' as _i6;
import 'package:core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_shows/presentation/bloc/tv_show_popular_bloc.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TvShowPopularBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowPopularBloc extends _i6.MockBloc<_i2.PopularEvent, _i2.PopularState> implements _i4.TvShowPopularBloc {}

class TvShowPopularEventFake extends _i1.Fake implements _i2.PopularEvent {}

class TvShowPopularStateFake extends _i1.Fake implements _i2.PopularState {}
