// Mocks generated by Mockito 5.0.15 from annotations
// in tv_shows/test/presentation/pages/top_rated_tv_shows_page_test.dart.
// Do not manually edit this file.

import 'package:bloc_test/bloc_test.dart';
import 'package:core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_shows/presentation/bloc/tv_show_top_rated_bloc.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TvShowTopRatedBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowTopRatedBloc extends MockBloc<_i2.TopRatedEvent, _i2.TopRatedState> implements _i4.TvShowTopRatedBloc {}

class TvShowTopRatedEventFake extends _i1.Fake implements _i2.TopRatedEvent {}

class TvShowTopRatedStateFake extends _i1.Fake implements _i2.TopRatedState {}
